version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bookexplorer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - C:/vsCode/Projetos/BookExplorer/backend/postgres:/var/lib/postgres
