version: "3.8"

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=book-explorer
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  mysql:
